add_newline = false
format = "$hostname$directory$git_branch$git_commit$git_state$character"

[character]
success_symbol = "[\\$](bold green)"
error_symbol = "[\\$](bold red)"

[hostname]
format = "[$hostname]($style):"
